version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=your_database_name
      - DB_USER=your_database_user
      - DB_PASSWORD=your_database_password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: